import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import { PageShell, Breadcrumb } from '../../design-system/layout';
import { Card, KpiCard } from '../../design-system/primitives';
import {
  EntityHeader,
  SpecsStrip,
  MethodologyCaveat,
  ColumnHeader,
  DataRow,
  Chevron,
  DeltaText,
} from '../../design-system/patterns';

import { historicalRepo, fleetRepo } from '../../data/repositories';
import { monogram } from '../../utils/format';

export default function VesselSummaryPage() {
  const { imo } = useParams();
  const navigate = useNavigate();
  const [vessel, setVessel] = useState(null);
  const [data, setData] = useState(null);

  useEffect(() => {
    Promise.all([fleetRepo.getByImo(imo), historicalRepo.getVesselBacktest(imo)]).then(
      ([v, d]) => {
        setVessel(v);
        setData(d);
      }
    );
  }, [imo]);

  if (!vessel || !data) {
    return (
      <PageShell>
        <div style={{ padding: 40, color: 'var(--color-text-secondary)' }}>Loading…</div>
      </PageShell>
    );
  }

  const { summary, voyages } = data;

  const meta = [
    `IMO ${vessel.imo}`,
    vessel.type,
    vessel.flag && `Flag ${vessel.flag}`,
    vessel.yearBuilt && `Built ${vessel.yearBuilt}`,
  ]
    .filter(Boolean)
    .join(' · ');

  const specs = [
    vessel.length && { label: 'Length', value: `${vessel.length} m` },
    vessel.beam && { label: 'Beam', value: `${vessel.beam} m` },
    vessel.draft && { label: 'Draft', value: `${vessel.draft} m` },
    vessel.grossTonnage && { label: 'GT', value: vessel.grossTonnage.toLocaleString() },
    vessel.deadweight && { label: 'DWT', value: vessel.deadweight.toLocaleString() },
  ].filter(Boolean);

  return (
    <PageShell>
      <div style={{ padding: '20px 20px 28px' }}>
        <Breadcrumb
          items={[{ label: 'Historical Analytics', to: '/history' }, { label: vessel.name }]}
        />
        <EntityHeader name={vessel.name} monogram={monogram(vessel.name)} meta={meta} />
        <SpecsStrip items={specs} />

        <SectionHeader title="Backtest summary" meta={`${summary.voyagesAnalyzed} voyages · ${summary.dateRange}`} />

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: 10,
            marginBottom: 12,
          }}
        >
          <KpiCard hero label="Cost saved" value={summary.costSaved.value} subValue={`${summary.costSaved.pct} vs actual`} subTone="success">
            <KpiSubLine label="Actual cost" value={summary.costSaved.actual} />
            <KpiSubLine label="Counterfactual" value={summary.costSaved.counterfactual} />
          </KpiCard>
          <KpiCard label="Time saved" value={summary.timeSaved.value} subValue={summary.timeSaved.pct} subTone="success">
            <KpiSubLine label="Actual port time" value={summary.timeSaved.actual} />
            <KpiSubLine label="Counterfactual" value={summary.timeSaved.counterfactual} />
          </KpiCard>
          <KpiCard label="Fuel saved" value={summary.fuelSaved.value} subValue={summary.fuelSaved.pct} subTone="success">
            <KpiSubLine label="Actual fuel" value={summary.fuelSaved.actual} />
            <KpiSubLine label="Counterfactual" value={summary.fuelSaved.counterfactual} />
          </KpiCard>
        </div>

        <MethodologyCaveat>
          <b>Methodology.</b> Recommendations regenerated by the production engine using only the
          AIS, vessel and port-state data available at each voyage's decision point. No hindsight.
          Fuel and cost are modelled estimates; assumptions: $620/t bunker, $2,400/h port time.
        </MethodologyCaveat>

        <div
          style={{
            display: 'grid',
            gridTemplateColumns: '1.4fr 1fr',
            gap: 12,
            marginBottom: 22,
          }}
        >
          <Card padding={14}>
            <SubTitle>Voyage outcomes</SubTitle>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 10, marginTop: 10 }}>
              <OutcomeCount value={summary.outcomes.improved} label="voyages improved" tone="gain" />
              <OutcomeCount value={summary.outcomes.neutral} label="no material change" tone="neutral" />
              <OutcomeCount value={summary.outcomes.worsened} label="voyages worsened" tone="loss" />
            </div>
          </Card>
          <Card padding={14}>
            <SubTitle>Per-voyage cost saved</SubTitle>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 10, marginTop: 10 }}>
              <OutcomeCount value={summary.perVoyage.avg} label="average" />
              <OutcomeCount value={summary.perVoyage.median} label="median" />
            </div>
          </Card>
        </div>

        <SectionHeader title="Voyages" meta="most recent first" />
        <ColumnHeader
          gap={12}
          gridTemplate="1.5fr 1.2fr 1fr 1fr 1.1fr 16px"
          columns={[
            { label: 'Route' },
            { label: 'Recommended profile' },
            { label: 'Time saved', align: 'right' },
            { label: 'Fuel saved', align: 'right' },
            { label: 'Cost saved', align: 'right' },
            { label: '' },
          ]}
        />
        {voyages.map((v) => (
          <DataRow
            key={v.id}
            onClick={() => navigate(`/history/${imo}/${v.id}`)}
            style={{ padding: '12px 16px' }}
          >
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: '1.5fr 1.2fr 1fr 1fr 1.1fr 16px',
                gap: 12,
                alignItems: 'center',
              }}
            >
              <div>
                <p style={{ fontSize: 13, fontWeight: 500, margin: '0 0 2px', lineHeight: 1.3 }}>
                  {v.routeFrom} → {v.routeTo}
                </p>
                <p
                  className="tabular"
                  style={{ fontSize: 11, color: 'var(--color-text-secondary)', margin: 0, lineHeight: 1.3 }}
                >
                  {v.dateRange}
                </p>
              </div>
              <p style={{ fontSize: 12, color: 'var(--color-text-secondary)', margin: 0, lineHeight: 1.3 }}>
                <b style={{ color: 'var(--color-text-primary)', fontWeight: 500 }}>
                  {v.recommendedProfile}
                </b>
              </p>
              <DeltaText value={v.timeSaved.value} delta={v.timeSaved.sub} tone={v.timeSaved.tone} colorValue />
              <DeltaText value={v.fuelSaved.value} delta={v.fuelSaved.sub} tone={v.fuelSaved.tone} colorValue />
              <DeltaText value={v.costSaved.value} delta={v.costSaved.sub} tone={v.costSaved.tone} colorValue />
              <Chevron />
            </div>
          </DataRow>
        ))}
      </div>
    </PageShell>
  );
}

function SectionHeader({ title, meta }) {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        marginBottom: 12,
      }}
    >
      <p style={{ fontSize: 14, fontWeight: 500, margin: 0 }}>{title}</p>
      {meta && (
        <p className="tabular" style={{ fontSize: 12, color: 'var(--color-text-secondary)', margin: 0 }}>
          {meta}
        </p>
      )}
    </div>
  );
}

function SubTitle({ children }) {
  return (
    <p
      style={{
        fontSize: 11,
        color: 'var(--color-text-tertiary)',
        margin: 0,
        textTransform: 'uppercase',
        letterSpacing: '0.04em',
        fontWeight: 500,
      }}
    >
      {children}
    </p>
  );
}

function KpiSubLine({ label, value }) {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: 11,
        color: 'var(--color-text-secondary)',
        padding: '3px 0',
        marginTop: 4,
      }}
      className="tabular"
    >
      <span>{label}</span>
      <b style={{ color: 'var(--color-text-primary)', fontWeight: 500 }}>{value}</b>
    </div>
  );
}

function OutcomeCount({ value, label, tone = 'default' }) {
  const colorMap = {
    gain: 'var(--color-text-success)',
    loss: 'var(--color-text-danger)',
    neutral: 'var(--color-text-secondary)',
    default: 'var(--color-text-primary)',
  };
  return (
    <div>
      <p
        className="tabular"
        style={{
          fontSize: 18,
          fontWeight: 500,
          color: colorMap[tone],
          margin: 0,
          lineHeight: 1.2,
        }}
      >
        {value}
      </p>
      <p style={{ fontSize: 11, color: 'var(--color-text-secondary)', margin: '4px 0 0', lineHeight: 1.3 }}>
        {label}
      </p>
    </div>
  );
}
